### ISSUE TITLE
Getting ModuleNotFound Error

### ISSUE THREAD

**Issue by mdabusiyam** [th3unkn0n/osi.ig#15]
python3 main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from api import *
  File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 3, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'

**Comment by th3unkn0n** [comment]
:facepalm: Install bs4 or run install.sh
https://pypi.org/project/bs4/
