### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by TheZLabs** [th3unkn0n/osi.ig#18]
I get this error when running the script. I am not sure what to make of it. I have python and python3 installed with everything necessary to my knowledge. Any help or suggestions would be appreciated.

[+] getting profile ...Traceback (most recent call last):
  File "main.py", line 16, in <module>
    ig = main(user=args["username"])
  File "/root/osi.ig/.lib/api.py", line 59, in __init__
    self.get_profile()
  File "/root/osi.ig/.lib/api.py", line 74, in get_profile
    self.p_data = self.data['entry_data']['ProfilePage'][0]['graphql']['user']
KeyError: 'ProfilePage'

**Comment by TheZLabs** [comment]
Went ahead and removed and ran through the installer again but the result was the same. Here is the output from installation:
![image](https://user-images.githubusercontent.com/59536236/86304036-9a595880-bbdb-11ea-8ef0-e96a4925f262.png)

**Comment by th3unkn0n** [comment]
can u share username you tried it on ??

**Comment by th3unkn0n** [comment]
@TheZLabs is it happening on all or specific users ?

**Comment by MnKMnK** [comment]
Same, it is across all users as well. I ran it as sudo su with login and just reg user, but outputs the exact same as above.

**Comment by hax0rx** [comment]
@MnKMnK @TheZLabs can u share ouput of this file ,
https://gist.githubusercontent.com/hax0rx/d55784ccc8b8a8af14ceb2abf44d3a35/raw/376a4143194ba14b1d000206ab2cee0e0bfccca9/test.py
it will be really helpful
