### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pboy192** [th3unkn0n/osi.ig#24]
Command: `python3 main.py -u USERNAME`

Result: `getting profile ...Traceback (most recent call last):                     File "main.py", line 16, in <module>
    ig = main(user=args["username"])                                          File "/root/tools/osi.ig/.lib/api.py", line 59, in __init__
    self.get_profile()                                                        File "/root/tools/osi.ig/.lib/api.py", line 74, in get_profile                self.p_data = self.data['entry_data']['ProfilePage'][0]['graphql']['user']                                                                          KeyError: 'ProfilePage'`

**Comment by solus-hq** [comment]
Same issue here.

**Comment by xen0s-0x00** [comment]
have you tried ?
pip3 install -r modules

**Comment by mass143** [comment]
CMD:- $ python2 main.py -u aaaaaaa
Result:-
Traceback (most recent call last):                                File "main.py", line 20, in <module>                              ig.print_data_()                                              File "/data/data/com.termux/files/home/desktop/osi.ig/.lib/api.py", line 115, in print_data_
    if self.tags == {}:
AttributeError: 'main' object has no attribute 'tags'

**Comment by thexen0s** [comment]
@mass143 its written python3

**Comment by th3unkn0n** [comment]
#25

**Comment by 010110011** [comment]
Traceback (most recent call last):                                File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in <module>                                                      user_info(usrname=args["user"])                               File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 71, in user_info                                                 js = js['graphql']['user']                                  KeyError: 'graphql'

**Comment by nikhilwankhedethecoder** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
~/osi.ig $

**Comment by RevoSan** [comment]
Traceback (most recent call last):
  File "/home/kali/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/home/kali/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MirzaSohaib-Baig** [comment]
same issue here

**Comment by ghost** [comment]
same issue 
What is the reason behind it ,
Can anyone resolve it.

**Comment by Kaiffkhan** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 70, in user_info                                 js = json.loads(resp_js)
         ^^^^^^^^^^^^^^^^^^^                              File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)                              ^^^^^^^^^^^^^^^^^^^^^^^^^^                     File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode                    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Same issue here

**Comment by ParagVadher** [comment]
same issue on centos 8

**Comment by Jatin9958217462** [comment]
**python main.py -u username**


Traceback (most recent call last):
  File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])                          File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
         ^^^^^^^^^^^^^^^^^^^                                 File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads                              return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                        File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode                          raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
**How to fix it this problem**

**Comment by Darklight2241** [comment]
![Screenshot_20230403-181510_Termux](https://user-images.githubusercontent.com/127670718/229510784-8634810d-5dd6-4c31-9465-7c90ae981611.jpg)
Can anyone solve

**Comment by Danial2169** [comment]
This own is just a dump

**Comment by ghost** [comment]
This owner is just a dump can't he fix that

**Comment by Jack07R** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in <module>                                                          user_info(usrname=args["user"])
  File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 70, in user_info                                                     js = json.loads(resp_js)
         ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads                                            return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode                                            obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^               File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode                                        raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sanjay55558** [comment]
Anyone got solution for this traceback error in termux... please could anyone help in this

**Comment by AyushKumar-01** [comment]
![Screenshot_2023-09-06-15-26-42-31_84d3000e3f4017145260f7618db1d683](https://github.com/th3unkn0n/osi.ig/assets/136918365/9aa08501-14c4-4006-87ae-7efe1c5bd55f)
Can somebody provide me the solution?

**Comment by Cshzivzjsvska** [comment]
![Screenshot_20231002-205857_Termux](https://github.com/th3unkn0n/osi.ig/assets/145892120/39097d0f-bd45-4bfe-95bf-6acaf787a151)
Please  solve problems

**Comment by Sharozhacker** [comment]
![Screenshot_20240105-171613_Termux](https://github.com/th3unkn0n/osi.ig/assets/155737864/0fa4eb02-dc96-4400-a892-74a84e9ffb4d)
Where is developer?

**Comment by Tasbeehkhan** [comment]
I think the developer.is sleeping

**Comment by armorkid** [comment]
line 16, in <module> user_info(usrname=args["user"])2

Tra

NameError: name 'user_info' is not defined
