### ISSUE TITLE
'charmap' codec can't encode characters in position 10-12: character maps to <undefined>

### ISSUE THREAD

**Issue by shahprog** [th3unkn0n/osi.ig#28]
```Traceback (most recent call last):
  File "main.py", line 20, in <module>
    ig.print_data_()
  File "C:\Users\Shahriyar\osi.ig/.lib\api.py", line 112, in print_data_
    extra.banner()
  File "C:\Users\Shahriyar\osi.ig/.lib\api.py", line 46, in banner
    print(f"""{cy}
  File "C:\Users\Shahriyar\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 10-12: character maps to <undefined>
```

**Comment by th3unkn0n** [comment]
it seems windows cmd error not script 
adding `.encoding("utf-8")` will work but i've used it only in linux so not sure
