### ISSUE TITLE
Code error 

### ISSUE THREAD

**Issue by CodeForg** [th3unkn0n/osi.ig#37]
Traceback (most recent call last):
  File "/home/tea_enjoyer/Desktop/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/home/tea_enjoyer/Desktop/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Not working idk why :(

**Comment by th3unkn0n** [comment]
is it happening for all account or one ?

**Comment by CodeForg** [comment]
For all

**Comment by CodeForg** [comment]
U can help me with that ?

**Comment by th3w4lk3r** [comment]
I have the same problem

**Comment by shurygindv** [comment]
https://stackoverflow.com/questions/57627864/instagram-user-page-parsing-with-proxy-without-api

when VPN is enabled: got response `Login HTML page` instead of enriched user data (and `json.loads` func throws an exception about unable parsing), probably, it's the restriction for unauthorized/suspicious using `Instagram API`

**Comment by th3unkn0n** [comment]
@shurygindv yes
@CodeForg there is way to kind of prevent this via login through insta acc but it will still block if too much requests are made so whole thing becomes pointless

**Comment by Ajay-singh1** [comment]
Giving code error.I think instagram is blocking suspicious application using the instagram API.

**Comment by C4l1b3r** [comment]
OK what I did to make it work (I'm on termux)
if not installed.pip install pipenv
pipenv install -r requirements.txt
pipenv shell
python main.py --user

**Comment by mzr-d3bz** [comment]
so how?

**Comment by TheETR** [comment]
> 

Still have the same error
