### ISSUE TITLE
.

### ISSUE THREAD

**Issue by kRisSaK-ui** [th3unkn0n/osi.ig#39]
У меня тоже такая ошибка 
Traceback (most recent call last):                                                                          File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
И как с ней бороться, я читал такие же комменты но я не понимаю как это сделать

**Comment by th3unkn0n** [comment]
этот комментарий объясняет причину #37. я постараюсь исправить это в следующем обновлении
