### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DSD-dev** [th3unkn0n/osi.ig#48]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 70, in user_info                                                                         js = json.loads(resp_js)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

here I can't even imagine how to fix it

**Comment by MountainSky67** [comment]
Same problem !

**Comment by MountainSky67** [comment]
Risolto....
Disinstallato - reinstallato !
