### ISSUE TITLE
Error traceback

### ISSUE THREAD

**Issue by AntoninoRoot** [th3unkn0n/osi.ig#51]
This what terminal says after enter the command for usage: 
Traceback (most recent call last):
  File "/home/kali/Desktop/insta/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/home/kali/Desktop/insta/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Anyone have a solution for this?

**Comment by git-lew** [comment]
same issue

**Comment by tony656** [comment]
same to me

**Comment by sh5263** [comment]
Same issue

**Comment by muchraezzy** [comment]
same...i think the solution is downgrading python

**Comment by th3unkn0n** [comment]
#37

**Comment by kushaljagtap025** [comment]
Is solution still not found
