### ISSUE TITLE
Error Traceback

### ISSUE THREAD

**Issue by vadly** [th3unkn0n/osi.ig#53]
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/home/msi/tools/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

can anyone help me?

**Comment by 89z** [comment]
Same error

**Comment by Prateek-420** [comment]
https://github.com/th3unkn0n/osi.ig/issues/37#issuecomment-756424850
