### ISSUE TITLE
Not working - Json error

### ISSUE THREAD

**Issue by Andrejki** [th3unkn0n/osi.ig#70]
```
```
Traceback (most recent call last):
  File "/home/andrejki/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/home/andrejki/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
osi.ig
```

```
Hey, thanks for this from the author, but people should be warned that this is definetely not working. 
It might be time to resolve this in a way that it would be working or not working because it is your repisotory and something needs to be done as you can see by all the people posting here. 
Best regards

**Comment by Andrejki** [comment]
Actually, it started working. 
Best regards

Yet, it won t give emails from public accounts. That is kind of... bad.

**Comment by Andrejki** [comment]
Hi. 
It works but just like once. Thank it gets to JSON errors. 
How to fix it?

**Comment by ahsentekd** [comment]
Instagram closed `?__a=1` so you cant gather any information.
