### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Abhiuday-Surya** [th3unkn0n/osi.ig#73]
Traceback (most recent call last):
  File "/home/kali/osi.ig/main.py", line 6, in <module>
    from api import *
  File "/home/kali/osi.ig/.lib/api.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by ahsentekd** [comment]
you need to install requests try this:
`pip3 install -r requirements.txt`
but still it wont work becaz instagram has closed ?__a=1 so you cant gather informations.

**Comment by ghost** [comment]
Same issue

**Comment by guts-ss** [comment]
> 
Did you find the solution??

**Comment by guts-ss** [comment]
> تحتاج إلى تثبيت الطلبات ، جرب هذا: `pip3 install -r requirements.txt` ولكن لا يزال الأمر كذلك لأن instagram قد أغلق؟ __ a = 1 لذلك لا يمكنك جمع المعلومات.

Did you find the solution??
