### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by NotRandom666** [th3unkn0n/osi.ig#79]
[+] getting profile ...Traceback (most recent call last):
  File "/home/thomas/ig.osi/main.py", line 16, in <module>
    ig = main(user=args["username"])
  File "/home/thomas/ig.osi/api.py", line 59, in __init__
    self.get_profile()
  File "/home/thomas/ig.osi/api.py", line 66, in get_profile
    self.data = json.loads(more_data[3].get_text()[21:].strip(';'))
IndexError: list index out of range

**Comment by vcbhai** [comment]
How to fix it
