### ISSUE TITLE
#show error on running

### ISSUE THREAD

**Issue by anikric** [th3unkn0n/osi.ig#9]
[+] getting profile ...Traceback (most recent call last):
  File "main.py", line 15, in <module>                ig = main(user=args["username"])                File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 51, in __init__
    self.get_profile()                              File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 58, in get_profile                   self.data = json.loads(more_data[3].get_text()[21:].strip(';'))                                   File "/data/data/com.termux/files/usr/lib/python3.8/json/__init__.py", line 357, in loads             return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
$

**Comment by keerthan95** [comment]
Same error

**Comment by th3unkn0n** [comment]
@anikric @KaravaliStudio update it fixed now
its was happening beacuse version diffrance in bs4 module
