### ISSUE TITLE
HELP ME PLEASE 

### ISSUE THREAD

**Issue by DragonRojo3** [th3unkn0n/osi.ig#93]
Traceback (most recent call last):
  File "/root/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/root/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by joshuadanpeterson** [comment]
Got the same error when trying to run the program

**Comment by Byanshuman** [comment]
same error
