### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by meyer-d3v** [th3unkn0n/osi.ig#96]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 70, in user_info                                       js = json.loads(resp_js)
         ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                        File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode                              obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode                          raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Marup006** [comment]
Same problem 😞

**Comment by marup2006** [comment]
> Traceback (most recent call last): File "/data/data/com.termux/files/home/osi.ig/main.py", line 16, in user_info(usrname=args["user"]) File "/data/data/com.termux/files/home/osi.ig/.lib/api.py", line 70, in user_info js = json.loads(resp_js) ^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/json/**init**.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Same problem 😔

**Comment by Royalroman123** [comment]
Same bro

**Comment by afaqizhar** [comment]
It's not working

**Comment by markshi9008** [comment]
> Same bro

Have your problem got solved, bro?

**Comment by Demugan** [comment]
I keep getting this error

**Comment by Demugan** [comment]
What is the solution?

**Comment by marup2006** [comment]
> What is the solution?

nope still not got solution from admin
